### ISSUE TITLE
Bot won't answer.

### ISSUE THREAD

**Issue by sosiska123331827255** [badgids/OpenKlyde#8]
![image](https://github.com/badgids/OpenKlyde/assets/109771573/12acb172-1e57-4d8f-b4a4-802967098e77)

When a prompt is entered in Discord, the bot.py file generates the following error. 

Maybe seeing it in text format will help better...
`C:\Users\User>python "C:\Users\User\Desktop\OpenKlyde-main\bot.py"
[2023-09-03 15:59:53] [INFO    ] discord.client: logging in using static token
[2023-09-03 15:59:53] [INFO    ] discord.gateway: Shard ID None has connected to Gateway (Session ID: ec8941b72865d1786f03b7c65b57549a).
Discord Bot is up and running.
[2023-09-03 15:59:55] [ERROR   ] discord.client: Ignoring exception in on_ready
Traceback (most recent call last):
  File "C:\Users\User\AppData\Local\Programs\Python\Python310\lib\site-packages\discord\client.py", line 441, in _run_event
    await coro(*args, **kwargs)
  File "C:\Users\User\Desktop\OpenKlyde-main\bot.py", line 257, in on_ready
    api_check = await functions.api_status_check(text_api["address"] + text_api["model"], headers=text_api["headers"])
KeyError: 'address'
[2023-09-03 16:00:19] [ERROR   ] discord.client: Ignoring exception in on_message
Traceback (most recent call last):
  File "C:\Users\User\AppData\Local\Programs\Python\Python310\lib\site-packages\discord\client.py", line 441, in _run_event
    await coro(*args, **kwargs)
  File "C:\Users\User\Desktop\OpenKlyde-main\bot.py", line 280, in on_message
    await update_status()
  File "C:\Users\User\Desktop\OpenKlyde-main\bot.py", line 49, in update_status
    data = await functions.check_bot_temps()
  File "C:\Users\User\Desktop\OpenKlyde-main\functions.py", line 15, in check_bot_temps
    return output.decode()
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x88 in position 39: invalid start byte
[2023-09-03 16:07:55] [ERROR   ] discord.client: Ignoring exception in on_message
Traceback (most recent call last):
  File "C:\Users\User\AppData\Local\Programs\Python\Python310\lib\site-packages\discord\client.py", line 441, in _run_event
    await coro(*args, **kwargs)
  File "C:\Users\User\Desktop\OpenKlyde-main\bot.py", line 280, in on_message
    await update_status()
  File "C:\Users\User\Desktop\OpenKlyde-main\bot.py", line 49, in update_status
    data = await functions.check_bot_temps()
  File "C:\Users\User\Desktop\OpenKlyde-main\functions.py", line 15, in check_bot_temps
    return output.decode()
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x88 in position 39: invalid start byte
[2023-09-03 16:07:56] [ERROR   ] discord.client: Ignoring exception in on_message
Traceback (most recent call last):
  File "C:\Users\User\AppData\Local\Programs\Python\Python310\lib\site-packages\discord\client.py", line 441, in _run_event
    await coro(*args, **kwargs)
  File "C:\Users\User\Desktop\OpenKlyde-main\bot.py", line 280, in on_message
    await update_status()
  File "C:\Users\User\Desktop\OpenKlyde-main\bot.py", line 49, in update_status
    data = await functions.check_bot_temps()
  File "C:\Users\User\Desktop\OpenKlyde-main\functions.py", line 15, in check_bot_temps
    return output.decode()
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x88 in position 39: invalid start byte
[2023-09-03 16:07:57] [ERROR   ] discord.client: Ignoring exception in on_message
Traceback (most recent call last):
  File "C:\Users\User\AppData\Local\Programs\Python\Python310\lib\site-packages\discord\client.py", line 441, in _run_event
    await coro(*args, **kwargs)
  File "C:\Users\User\Desktop\OpenKlyde-main\bot.py", line 280, in on_message
    await update_status()
  File "C:\Users\User\Desktop\OpenKlyde-main\bot.py", line 49, in update_status
    data = await functions.check_bot_temps()
  File "C:\Users\User\Desktop\OpenKlyde-main\functions.py", line 15, in check_bot_temps
    return output.decode()
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x88 in position 39: invalid start byte
[2023-09-03 16:10:03] [ERROR   ] discord.client: Ignoring exception in on_message
Traceback (most recent call last):
  File "C:\Users\User\AppData\Local\Programs\Python\Python310\lib\site-packages\discord\client.py", line 441, in _run_event
    await coro(*args, **kwargs)
  File "C:\Users\User\Desktop\OpenKlyde-main\bot.py", line 280, in on_message
    await update_status()
  File "C:\Users\User\Desktop\OpenKlyde-main\bot.py", line 49, in update_status
    data = await functions.check_bot_temps()
  File "C:\Users\User\Desktop\OpenKlyde-main\functions.py", line 15, in check_bot_temps
    return output.decode()
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x88 in position 39: invalid start byte
[2023-09-03 16:10:04] [ERROR   ] discord.client: Ignoring exception in on_message
Traceback (most recent call last):
  File "C:\Users\User\AppData\Local\Programs\Python\Python310\lib\site-packages\discord\client.py", line 441, in _run_event
    await coro(*args, **kwargs)
  File "C:\Users\User\Desktop\OpenKlyde-main\bot.py", line 280, in on_message
    await update_status()
  File "C:\Users\User\Desktop\OpenKlyde-main\bot.py", line 49, in update_status
    data = await functions.check_bot_temps()
  File "C:\Users\User\Desktop\OpenKlyde-main\functions.py", line 15, in check_bot_temps
    return output.decode()
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x88 in position 39: invalid start byte
[2023-09-03 16:10:17] [ERROR   ] discord.client: Ignoring exception in on_message
Traceback (most recent call last):
  File "C:\Users\User\AppData\Local\Programs\Python\Python310\lib\site-packages\discord\client.py", line 441, in _run_event
    await coro(*args, **kwargs)
  File "C:\Users\User\Desktop\OpenKlyde-main\bot.py", line 280, in on_message
    await update_status()
  File "C:\Users\User\Desktop\OpenKlyde-main\bot.py", line 49, in update_status
    data = await functions.check_bot_temps()
  File "C:\Users\User\Desktop\OpenKlyde-main\functions.py", line 15, in check_bot_temps
    return output.decode()
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x88 in position 39: invalid start byte
[2023-09-03 16:10:17] [ERROR   ] discord.client: Ignoring exception in on_message
Traceback (most recent call last):
  File "C:\Users\User\AppData\Local\Programs\Python\Python310\lib\site-packages\discord\client.py", line 441, in _run_event
    await coro(*args, **kwargs)
  File "C:\Users\User\Desktop\OpenKlyde-main\bot.py", line 280, in on_message
    await update_status()
  File "C:\Users\User\Desktop\OpenKlyde-main\bot.py", line 49, in update_status
    data = await functions.check_bot_temps()
  File "C:\Users\User\Desktop\OpenKlyde-main\functions.py", line 15, in check_bot_temps
    return output.decode()
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x88 in position 39: invalid start byte
[2023-09-03 16:10:53] [ERROR   ] discord.client: Ignoring exception in on_message
Traceback (most recent call last):
  File "C:\Users\User\AppData\Local\Programs\Python\Python310\lib\site-packages\discord\client.py", line 441, in _run_event
    await coro(*args, **kwargs)
  File "C:\Users\User\Desktop\OpenKlyde-main\bot.py", line 280, in on_message
    await update_status()
  File "C:\Users\User\Desktop\OpenKlyde-main\bot.py", line 49, in update_status
    data = await functions.check_bot_temps()
  File "C:\Users\User\Desktop\OpenKlyde-main\functions.py", line 15, in check_bot_temps
    return output.decode()
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x88 in position 39: invalid start byte`

**Comment by sosiska123331827255** [comment]
![image](https://github.com/badgids/OpenKlyde/assets/109771573/d9fbc26f-d92c-44bc-b435-7619239cf516)
Yes, I did create it.

And right now as I see, bot actually turns on, but for some reason error occured after turning the bot on, not because I typed something in. 

![image](https://github.com/badgids/OpenKlyde/assets/109771573/cef2cfe8-91be-4b7a-9b60-d1c5c131d31e)

Same error everytime I turn it in.

**Comment by badgids** [comment]
Try renaming "context" with a lowercase "c". It places your querry in a text file there and then parses it. My first quess is that file isn't being created, so nothing is being sent, throwing the utf-8 error. 

I noticed you've had one hell of a time getting any LLM Discord bot working. So let's do a little troubleshooting.

Make sure you edited any text file with a real text editor like VSCode, Notepad, Notepad++, etc. not any RTF type text editor.

If you're using KoboldAI your port number in  "OpenKlyde\configurations\text-default.json" needs to read port 5000, if using Koboldcpp it needs to be port 5001. If "localhost" doesn't work on your system, try changong it to:

```
"address": "http://0.0.0.0:5001/api/v1/",
```

or 

```
"address": "http://127.0.0.1:5001/api/v1/",
```

If you have koboldcpp running on a different machine, and/or a different port than the default, you wil need to change this line to match the correct IP address and port number.

**Comment by badgids** [comment]
What's your local? I hardcoded utf-8 because I'm apparently an arrogant American. lol.

**Comment by badgids** [comment]
Oh... wait a minute... Your local... lol. Your Username, does it contain non ascii characters, perhaps? I noticed a few in your screenshots. ;) let's try this.... At the top of bot.py, and any other file that's giving you issues, try adding:

```
# -*- coding: utf-8 -*-
```

That SHOULD force it to use utf-8 encoding. I honestly have no way to test it out myself.

**Comment by badgids** [comment]
Line 348 of "bot.by" declares the encoding, you could try chaning this too.

**Comment by sosiska123331827255** [comment]
> Make sure you edited any text file with a real text editor like VSCode, Notepad, Notepad++, etc. not any RTF type text editor.

I am editing the file with Notepad++.

> If you're using KoboldAI your port number in "OpenKlyde\configurations\text-default.json" needs to read port 5000, if using Koboldcpp it needs to be port 5001.

I am using "coboldcpp". The localhost is working. 
![image](https://github.com/badgids/OpenKlyde/assets/109771573/59307c3b-84a0-4b04-a31e-1520b9a344e9)

> Let me know if any of ths helps, fixes it, makes it worse, breaks everything, spirarals the world powers into WWIII, etc

lol. Koboldcpp started threatening to take over the world, and kill all my family. Is this normal? 
By the way, 
![image](https://github.com/badgids/OpenKlyde/assets/109771573/83503cff-06c6-4bbb-8663-5fba4b3c749e)
Changing emojis didn't really help. 
Adding `# -*- coding: utf-8 -*-` didn't help.
> Oh... wait a minute... Your local... lol. Your Username, does it contain non ascii characters, perhaps? I noticed a few in your screenshots. ;) 

Non-ascii characters? Sounds alien. What are those?  

> - Check line 348 of "bot.py" to declare the encoding and adjust it if necessary. 
> - Ensure that PyTorch is installed in a directory with a path containing only ASCII characters, as some libraries like PyTorch expect UTF-8 formatted file directories.

**Comment by sosiska123331827255** [comment]
jez i am an idiot. I thought you meant at beginning of every program file, not script...

**Comment by sosiska123331827255** [comment]
Well...
![image](https://github.com/badgids/OpenKlyde/assets/109771573/8a4be9c9-723c-456b-8e2b-f34dd4671f44)
![image](https://github.com/badgids/OpenKlyde/assets/109771573/527a4d60-7853-42f2-888c-1d1cf3128ab3)
![image](https://github.com/badgids/OpenKlyde/assets/109771573/56783f0c-eadf-4858-9a43-7ab23e3a3de2)

Still gives me an error. 
![image](https://github.com/badgids/OpenKlyde/assets/109771573/a61a8eec-74aa-4d96-b101-8398bb24dc4b)
